In [2]:
import numpy as np

# Creating Numpy Arrays from Python Lists

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
[3.14, 1, 2, 3]

[3.14, 1, 2, 3]

In [5]:
np.array([3.14, 1, 2, 3])

array([3.14, 1.  , 2.  , 3.  ])

In [6]:
[1, 2, 3, 3.14]

[1, 2, 3, 3.14]

In [7]:
np.array([1, 2, 3, 3.14])

array([1.  , 2.  , 3.  , 3.14])

In [8]:
np.array([1, 2, 3, 3.14], dtype="float32")

array([1.  , 2.  , 3.  , 3.14], dtype=float32)

In [9]:
np.array([1, 2, 3, 3.14], dtype="int32")

array([1, 2, 3, 3], dtype=int32)

In [10]:
a1 = np.array([1, 2, 3, 3.14])

In [11]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [15]:
type(a2)

numpy.ndarray

In [16]:
a2.shape

(2, 4)

In [17]:
a1.ndim

1

In [18]:
a2.ndim

2

In [19]:
a2.dtype

dtype('int64')

In [20]:
a2.size

8

In [21]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Creating Numpy Arrays from Scratch

### zeros, ones, full, arange, linspace

In [69]:
np.zeros((2, 4), dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
np.ones((3, 5), dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
np.full((3, 5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [73]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### random

In [74]:
# Seed for reproducibility
np.random.seed(0)

np.random.random((3, 5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [75]:
# np.random.random((3, 5))

In [76]:
np.random.rand(4, 4)

array([[0.0871293 , 0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194, 0.26455561]])

In [77]:
np.random.normal(0, 1, (3, 3))

array([[-0.24214951,  1.51439128, -0.3330574 ],
       [ 0.04736482,  1.46274045,  1.53502913],
       [ 0.56644004,  0.14926509, -1.078278  ]])

In [78]:
np.random.randint(0, 10, (3, 3))

array([[8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]], dtype=int32)

## Array Indexing & Slicing

### One-dimensional subarray

In [79]:
x1 = np.random.randint(20, size = 6)

In [80]:
x1

array([11, 14, 18,  0, 14,  3], dtype=int32)

In [81]:
x1[4], x1[0], x1[-1]

(np.int32(14), np.int32(11), np.int32(3))

### Multi-dimensional array

In [82]:
x2 = np.random.randint(10, size = (3, 4))

In [83]:
x2

array([[5, 9, 4, 4],
       [6, 4, 4, 3],
       [4, 4, 8, 4]], dtype=int32)

In [84]:
x2[1, 2]

np.int32(4)

In [85]:
x2[1, 2] = 6

In [86]:
x2

array([[5, 9, 4, 4],
       [6, 4, 6, 3],
       [4, 4, 8, 4]], dtype=int32)

### Slicing

In [87]:
x1

array([11, 14, 18,  0, 14,  3], dtype=int32)

In [88]:
x1[0:3]

array([11, 14, 18], dtype=int32)

In [89]:
x1[2:4]

array([18,  0], dtype=int32)

In [90]:
x1[::2]

array([11, 18, 14], dtype=int32)

In [91]:
x1[1::2]

array([14,  0,  3], dtype=int32)

In [92]:
x2

array([[5, 9, 4, 4],
       [6, 4, 6, 3],
       [4, 4, 8, 4]], dtype=int32)

In [93]:
# tow rows, three columns
x2[:2, :3]

array([[5, 9, 4],
       [6, 4, 6]], dtype=int32)

In [94]:
x2[:2, 1:3]

array([[9, 4],
       [4, 6]], dtype=int32)

In [95]:
x2[:2, :3]

array([[5, 9, 4],
       [6, 4, 6]], dtype=int32)